### PR TITLE
Steps visualization, total and month

### LINKED ISSUE #29: Steps report should take real steps
Schermata 2021-11-25 alle 11 17 24

### PR DESCRIPTION
**Pull request by SimoravaIT**

### CODE REVIEW

**Comment by edogab33** [comment]
Simone, is the code all tested and working as expected? Especially the database queries

**Comment by SimoravaIT** [comment]
> Simone, is the code all tested and working as expected? Especially the database queries

I think yes, i also commented the method it should be easy to check if I remember correctly. The only problem I found is about the syncronization, the 3 steps counters are not updated at the same time but it shuldn't be a problem

**Comment by edogab33** [comment]
> > Simone, is the code all tested and working as expected? Especially the database queries
> 
> I think yes, i also commented the method it should be easy to check if I remember correctly. The only problem I found is about the syncronization, the 3 steps counters are not updated at the same time but it shuldn't be a problem

Ok, I'll merge it because I need to write some code in the database controller and I don't want to manage conflicts but test all the methods you implemented here as soon as you have time

**Comment by SimoravaIT** [comment]
> 

Yes of course, I tested them, if something is wrong is because I didn't noticed it unfortunately

**Pull request merged**
